-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3DGgXbIQtfwMK7YU
3BycTfTFfzdmknbDwu5Tms3kpdSgCgYIKoZIzj0DAQehRANCAARzZ7w/cBgBAqBr
zJvuPkhEcCoe+o7egSJTEaeol3D5tuTFtjKWEA+g01EsQcnq3Xe7EIFuhvr0kCLm
YKNJOclI
-----END PRIVATE KEY-----